package com.dev.generik.repository.ERM.SP;

import java.util.Date;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.repository.query.Param;

import com.dev.generik.entities.ERM.SP.SPLab;

public interface SPLabRepository extends JpaRepository<SPLab, Long> {
	
	//<SPLab>findByNo(Long no);
	
	@Procedure(name = "UpdateSPLab")
	void updateSPLab(
			@Param("NO") Long no,
			@Param("ID") Long id, 
			@Param("IDDokter") Long iddokter, 
		//	@Param("OK") Boolean ok,
			@Param("TGL") Date tgl, 
			@Param("Jam") Date jam, 
			@Param("HeDL") Boolean heDL,			
			@Param("HeHemo") Boolean HeHemo,
			@Param("HeLeko") Boolean HeLeko,
			@Param("HeHema") Boolean HeHema,
			@Param("HeEri") Boolean HeEri,
			@Param("HeLajuEnDa") Boolean HeLajuEnDa,
			@Param("HeTrombo") Boolean HeTrombo,
			@Param("HeReti") Boolean HeReti,
			@Param("HeHitung") Boolean HeHitung,
			@Param("HeSerum") Boolean HeSerum,
			@Param("HeTIBC") Boolean HeTIBC,
			@Param("FHelPPT") Boolean FHelPPT,
			@Param("FHeAPTT") Boolean FHeAPTT,
			@Param("FHeCT") Boolean FHeCT,
			@Param("FHeBT") Boolean FHeBT,
			@Param("FHeINR") Boolean FHeINR,
			@Param("FHeGolDar") Boolean FHeGolDar,
			@Param("FHeGolDarRe") Boolean FHeGolDarRe,
			@Param("FHeHapusanDar") Boolean FHeHapusanDar,
			@Param("UL") Boolean UL,
			@Param("FcesFL") Boolean FcesFL,
			@Param("FcesBenzi") Boolean FcesBenzi,
			@Param("FHaBiliTotal") Boolean FHaBiliTotal,
			@Param("FHaBiliDerek") Boolean FHaBiliDerek,
			@Param("FHaBiliInDerek") Boolean FHaBiliInDerek,
			@Param("FHaSGOT") Boolean FHaSGOT,
			@Param("FHaSGPT") Boolean FHaSGPT,
			@Param("FHaAlkali") Boolean FHaAlkali,
			@Param("FHaTotalPro") Boolean FHaTotalPro,
			@Param("FHaAlbu") Boolean FHaAlbu,
			@Param("FHaGlo") Boolean FHaGlo,
			@Param("FGinKre") Boolean FGinKre,
			@Param("FGinUreun") Boolean FGinUreun,
			@Param("FGinUridAcid") Boolean FGinUridAcid,
			@Param("LemDarChole") Boolean LemDarChole,
			@Param("LemDarHDL") Boolean LemDarHDL,
			@Param("LemDarLDL") Boolean LemDarLDL,
			@Param("LemDarTri") Boolean LemDarTri,
			@Param("GDGlu") Boolean GDGlu,
			@Param("GDGlu2jam") Boolean GDGlu2jam,
			@Param("GDGlusesaat") Boolean GDGlusesaat,
			@Param("GDHbA1c") Boolean GDHbA1c,
			@Param("Ele") Boolean Ele,
			@Param("EleNat") Boolean EleNat,
			@Param("EleKal") Boolean EleKal,
			@Param("EleClo") Boolean EleClo,
			@Param("EleCal") Boolean EleCal,
			@Param("ImHBsAg") Boolean ImHBsAg,
			@Param("ImAnHBs") Boolean ImAnHBs,
			@Param("ImHBsAgTiter") Boolean ImHBsAgTiter,
			@Param("ImAnHBsAgTiter") Boolean ImAnHBsAgTiter,
			@Param("ImAnHCV") Boolean ImAnHCV,
			@Param("ImAnHAVIgG") Boolean ImAnHAVIgG,
			@Param("ImAnIgM") Boolean ImAnIgM,
			@Param("ImInWidal") Boolean ImInWidal,
			@Param("ImInAntiDhf") Boolean ImInAntiDhf,
			@Param("ImInVDRL") Boolean ImInVDRL,
			@Param("ImInAntiHIV") Boolean ImInAntiHIV,
			@Param("ImInMala") Boolean ImInMala,
			@Param("ImInScreHIV") Boolean ImInScreHIV,
			@Param("ImInASO") Boolean ImInASO,
			@Param("ImInCRP") Boolean ImInCRP,
			@Param("ImInAna") Boolean ImInAna,
			@Param("ImInTubex") Boolean ImInTubex,
			@Param("ImInMantoux") Boolean ImInMantoux,			
			@Param("ImInIgGAnToxo") Boolean ImInIgGAnToxo,
			@Param("ImInIgMAnToxo") Boolean ImInIgMAnToxo,
			@Param("ImInIgGAnRub") Boolean ImInIgGAnRub,
			@Param("ImInIgMAnRub") Boolean ImInIgMAnRub,
			@Param("ImInIgGAnCMV") Boolean ImInIgGAnCMV,
			@Param("ImInIgMAnCMV") Boolean ImInIgMAnCMV,
			@Param("ImInIgGAnHSV1") Boolean ImInIgGAnHSV1,
			@Param("ImInIgMAnHSV1") Boolean ImInIgMAnHSV1,
			@Param("ImInIgGAnHSV2") Boolean ImInIgGAnHSV2,
			@Param("ImInIgMAnHSV2") Boolean ImInIgMAnHSV2,
			@Param("HamPlano") Boolean HamPlano,			
			@Param("HamTestPack") Boolean HamTestPack,
			@Param("HamPlanoPengen") Boolean HamPlanoPengen,
			@Param("TumAFP") Boolean TumAFP,
			@Param("TumCEA") Boolean TumCEA,
			@Param("TumPSA") Boolean TumPSA,
			@Param("TumCa125") Boolean TumCa125,
			@Param("TumCa19") Boolean TumCa19,
			@Param("TirTSH") Boolean TirTSH,
			@Param("TirFT3") Boolean TirFT3,
			@Param("TirFT4") Boolean TirFT4,
			@Param("JanTrop") Boolean JanTrop,
			@Param("JanOk") Boolean JanOk,
			@Param("JanTropI") Boolean JanTropI,
			@Param("MikZN") Boolean MikZN,
			@Param("MikNeis") Boolean MikNeis,			
			@Param("MikGram") Boolean MikGram,
			@Param("MikMal") Boolean MikMal,
			@Param("MikKulDar") Boolean MikKulDar,
			@Param("MikKulUr") Boolean MikKulUr,
			@Param("MikSpu") Boolean MikSpu,
			@Param("GD") Boolean GD,
			@Param("LainAnSper") Boolean LainAnSper,
			@Param("LainAnBatGin") Boolean LainAnBatGin,
			@Param("LainRap") Boolean LainRap,
			@Param("LainODim") Boolean LainODim,
			@Param("Lain") String Lain,
			@Param("KelasID") Long KelasID,
			@Param("RoomID") Long RoomID,
			@Param("Diagnosa") String Diagnosa
			);
}