package com.dev.generik.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.data.rest.core.config.RepositoryRestConfiguration;
import org.springframework.data.rest.webmvc.config.RepositoryRestConfigurer;
import org.springframework.web.servlet.config.annotation.CorsRegistry;

import com.dev.generik.entities.Inacbg;
import com.dev.generik.entities.Dokter.Dokter;
import com.dev.generik.entities.Dokter.LoginDokter;
import com.dev.generik.entities.Dokter.Specialist;
import com.dev.generik.entities.Dokter.SpecialistB;
import com.dev.generik.entities.Dokter.SpecialistOL;
import com.dev.generik.entities.Dokter.VisitDokter;
import com.dev.generik.entities.Dokter.VisiteDokterOnsite;
import com.dev.generik.entities.Dokter.WebDokter;
import com.dev.generik.entities.ERM.IGD.ERMIGDObservasi;
import com.dev.generik.entities.ERM.IGD.ERMIGDObservasiCPPT;
import com.dev.generik.entities.ERM.IGD.ERMIGDPengkajianAwalAnalisaNRencana;
import com.dev.generik.entities.ERM.IGD.ERMIGDPengkajianAwalAnalisaNRencanaKep;
import com.dev.generik.entities.ERM.IGD.ERMIGDPengkajianAwalDischargePlanning;
import com.dev.generik.entities.ERM.IGD.ERMIGDPengkajianAwalFungJatuhPopulasiEdukasi;
import com.dev.generik.entities.ERM.IGD.ERMIGDPengkajianAwalKep;
import com.dev.generik.entities.ERM.IGD.ERMIGDPengkajianAwalMedis;
import com.dev.generik.entities.ERM.IGD.ERMIGDPengkajianAwalNyeri;
import com.dev.generik.entities.ERM.IGD.ERMIGDPengkajianAwalPsikoEkoNut;
import com.dev.generik.entities.ERM.IGD.ERMIGDPengkajianAwalTriage;
import com.dev.generik.entities.ERM.IGD.SkriningCovid.ERMIGDSkriningCovid;
import com.dev.generik.entities.ERM.IGD.SkriningTB.ERMIGDSkriningTB;
import com.dev.generik.entities.ERM.Lab.PxRJAntiPCR;
import com.dev.generik.entities.ERM.Rad.Radiologi;
import com.dev.generik.entities.ERM.Rad.RadiologiBaca;
import com.dev.generik.entities.ERM.SP.SPLab;
import com.dev.generik.entities.HaloRSA.BedReady;
import com.dev.generik.entities.HaloRSA.BedReadyBPJS;
import com.dev.generik.entities.HaloRSA.Berita;
import com.dev.generik.entities.HaloRSA.BeritaNew;
import com.dev.generik.entities.HaloRSA.CekPx;
import com.dev.generik.entities.HaloRSA.NoWaAndroid;
import com.dev.generik.entities.HaloRSA.NonUSGXRayCT;
import com.dev.generik.entities.HaloRSA.NonUSGXRayCTId;
import com.dev.generik.entities.HaloRSA.PxNewOL;
import com.dev.generik.entities.HaloRSA.PxRJPCRALL;
import com.dev.generik.entities.HaloRSA.QuePx;
import com.dev.generik.entities.HaloRSA.RatingRegNew;
import com.dev.generik.entities.HaloRSA.Reg;
import com.dev.generik.entities.HaloRSA.RegNewOL;
import com.dev.generik.entities.HaloRSA.RegNewOLT;
import com.dev.generik.entities.HaloRSA.RegPxOLNew;
import com.dev.generik.entities.HaloRSA.RiwayatReg;
import com.dev.generik.entities.HaloRSA.Slide;
import com.dev.generik.entities.HaloRSA.SurveyNewOL;
import com.dev.generik.entities.Inap.InfoBill;
import com.dev.generik.entities.Inap.ListPxInap;
import com.dev.generik.entities.Inap.Paviliun;
import com.dev.generik.entities.Inap.Pelayanan;
import com.dev.generik.entities.Inap.PxInapOnsite;
import com.dev.generik.entities.Inap.TracerPXPlg;
import com.dev.generik.entities.Inap.TracerPXRI;
import com.dev.generik.entities.JadwalDokter.JadwalDokter;
import com.dev.generik.entities.JadwalDokter.JadwalDokterDisplay;
import com.dev.generik.entities.JadwalDokter.JadwalDokterHr;
import com.dev.generik.entities.JadwalDokter.JadwalDokterPrak;
import com.dev.generik.entities.JadwalDokter.JadwalDokterPrakLab;
import com.dev.generik.entities.JadwalDokter.JadwalDokterPrakV2;
import com.dev.generik.entities.JadwalOP.JadOPBPJS;
import com.dev.generik.entities.JadwalOP.JadwalOperasi;
import com.dev.generik.entities.JadwalOP.JadwalOperasiNow;
import com.dev.generik.entities.JadwalOP.JadwalOperasiPen;
import com.dev.generik.entities.Lab.GeNose;
import com.dev.generik.entities.Lab.HasilPCR;
import com.dev.generik.entities.Lab.HasilPCRWS;
import com.dev.generik.entities.Lab.Lab;
import com.dev.generik.entities.Lab.LabAntigen;
import com.dev.generik.entities.Lab.LabHasil;
import com.dev.generik.entities.Lab.LabHasilLevel;
import com.dev.generik.entities.Lab.PCRExternal;
import com.dev.generik.entities.Lab.PCRExternalView;
import com.dev.generik.entities.Lab.PCRRekanan;
import com.dev.generik.entities.PSDI.Diklat;
import com.dev.generik.entities.PSDI.DiklatNew;
import com.dev.generik.entities.PX.Kecamatan;
import com.dev.generik.entities.PX.Kelurahan;
import com.dev.generik.entities.PX.Pasien;
import com.dev.generik.entities.PX.Pendidikan;
import com.dev.generik.entities.PX.Propinsi;
import com.dev.generik.entities.PX.PxId;
import com.dev.generik.entities.PX.PxInfo;
import com.dev.generik.entities.PX.Suku;
import com.dev.generik.entities.Que.AntrianKORJ;
import com.dev.generik.entities.RJ.ListPxRJNow;
import com.dev.generik.entities.RJ.StatusTransaksiRJ;
import com.dev.generik.entities.RJ.TaskIDIRJ;
import com.dev.generik.entities.Rad.RadiologiBacaPeriksa;
import com.dev.generik.entities.TB.TB03;
import com.dev.generik.entities.TB.TB06;
import com.dev.generik.entities.TB.TBICD;
import com.dev.generik.entities.TB.TBScreaningRI;
import com.dev.generik.entities.TB.TBScreaningRJ;

@Configuration
public class HisWebConfig implements RepositoryRestConfigurer {

    @Override
    public void configureRepositoryRestConfiguration(
      RepositoryRestConfiguration config, CorsRegistry cors) {
        config.exposeIdsFor(Dokter.class);
        config.exposeIdsFor(BedReady.class);
        config.exposeIdsFor(BedReadyBPJS.class);
        config.exposeIdsFor(Berita.class);
        config.exposeIdsFor(BeritaNew.class);
        config.exposeIdsFor(CekPx.class);
        config.exposeIdsFor(Diklat.class);
        config.exposeIdsFor(DiklatNew.class);
        config.exposeIdsFor(GeNose.class);
        config.exposeIdsFor(HasilPCR.class);
        config.exposeIdsFor(HasilPCRWS.class);
        config.exposeIdsFor(Inacbg.class);
        config.exposeIdsFor(InfoBill.class);
        config.exposeIdsFor(JadOPBPJS.class);
        config.exposeIdsFor(JadwalDokter.class);
        config.exposeIdsFor(JadwalDokterDisplay.class);
        config.exposeIdsFor(JadwalDokterHr.class);
        config.exposeIdsFor(JadwalDokterPrak.class);
        config.exposeIdsFor(JadwalDokterPrakLab.class);
        config.exposeIdsFor(JadwalDokterPrakV2.class);
        config.exposeIdsFor(JadwalOperasi.class);
        config.exposeIdsFor(JadwalOperasiNow.class);
        config.exposeIdsFor(JadwalOperasiPen.class);
        config.exposeIdsFor(Kecamatan.class);
        config.exposeIdsFor(Kelurahan.class);
        config.exposeIdsFor(Lab.class);
        config.exposeIdsFor(LabAntigen.class);
        config.exposeIdsFor(LabHasil.class);
        config.exposeIdsFor(LabHasilLevel.class);
        config.exposeIdsFor(ListPxInap.class);
        config.exposeIdsFor(ListPxRJNow.class);
        config.exposeIdsFor(LoginDokter.class);
        config.exposeIdsFor(NonUSGXRayCT.class);
        config.exposeIdsFor(NonUSGXRayCTId.class);
        config.exposeIdsFor(NoWaAndroid.class);
        config.exposeIdsFor(Pasien.class);        
        config.exposeIdsFor(Paviliun.class);
        config.exposeIdsFor(PCRExternal.class);
        config.exposeIdsFor(PCRExternalView.class);
        config.exposeIdsFor(PCRRekanan.class);
        config.exposeIdsFor(Pelayanan.class);
        config.exposeIdsFor(Pendidikan.class);
        config.exposeIdsFor(Propinsi.class);
        config.exposeIdsFor(PxId.class);
        config.exposeIdsFor(PxInapOnsite.class);
        config.exposeIdsFor(PxInfo.class);
        config.exposeIdsFor(PxNewOL.class);
        config.exposeIdsFor(PxRJAntiPCR.class);
        config.exposeIdsFor(PxRJPCRALL.class);
        config.exposeIdsFor(QuePx.class);
        config.exposeIdsFor(Radiologi.class);
        config.exposeIdsFor(RadiologiBaca.class);
        config.exposeIdsFor(RadiologiBacaPeriksa.class);
        config.exposeIdsFor(RatingRegNew.class);
        config.exposeIdsFor(Reg.class);
        config.exposeIdsFor(RegNewOL.class);
        config.exposeIdsFor(RegNewOLT.class);
        config.exposeIdsFor(RegPxOLNew.class);
        config.exposeIdsFor(RiwayatReg.class);
        config.exposeIdsFor(Slide.class);
        config.exposeIdsFor(Specialist.class);
        config.exposeIdsFor(SpecialistB.class);
        config.exposeIdsFor(SpecialistOL.class);
        config.exposeIdsFor(StatusTransaksiRJ.class);
        config.exposeIdsFor(Suku.class);
        config.exposeIdsFor(SurveyNewOL.class);
        config.exposeIdsFor(TaskIDIRJ.class);        
        config.exposeIdsFor(TB03.class);
        config.exposeIdsFor(TB06.class);
        config.exposeIdsFor(TBICD.class);
        config.exposeIdsFor(TBScreaningRI.class);
        config.exposeIdsFor(TBScreaningRJ.class);        
        config.exposeIdsFor(TracerPXPlg.class);
        config.exposeIdsFor(TracerPXRI.class);
        config.exposeIdsFor(VisitDokter.class);
        config.exposeIdsFor(VisiteDokterOnsite.class);
        config.exposeIdsFor(WebDokter.class);
        config.exposeIdsFor(AntrianKORJ.class);        
        config.exposeIdsFor(ERMIGDObservasi.class);
        config.exposeIdsFor(ERMIGDObservasiCPPT.class);
        config.exposeIdsFor(ERMIGDPengkajianAwalAnalisaNRencana.class);
        config.exposeIdsFor(ERMIGDPengkajianAwalAnalisaNRencanaKep.class);
        config.exposeIdsFor(ERMIGDPengkajianAwalDischargePlanning.class);
        config.exposeIdsFor(ERMIGDPengkajianAwalFungJatuhPopulasiEdukasi.class);
        config.exposeIdsFor(ERMIGDPengkajianAwalKep.class);
        config.exposeIdsFor(ERMIGDPengkajianAwalMedis.class);
        config.exposeIdsFor(ERMIGDPengkajianAwalNyeri.class);
        config.exposeIdsFor(ERMIGDPengkajianAwalPsikoEkoNut.class);
        config.exposeIdsFor(ERMIGDPengkajianAwalTriage.class);
        config.exposeIdsFor(ERMIGDSkriningCovid.class);
        config.exposeIdsFor(ERMIGDSkriningTB.class);
        config.exposeIdsFor(SPLab.class);
    }
}